mysql+pymysql://sql8507066:8Dh6qETGM5@sql8.freemysqlhosting.net:3306/sql8507066
Connection to the sql8.freemysqlhosting.net for user sql8507066 created successfully.
Verifying state: 0011622278
gate being used: OUT
Query Executing: SELECT * FROM users WHERE rf_id="0011622278" 
user with card 0011622278 does not exist
Verifying state: 0011633666
gate being used: OUT
Query Executing: SELECT * FROM users WHERE rf_id="0011633666" 
Query Executing: SELECT * FROM access_logs WHERE rf_id="0011633666" ORDER BY id  DESC LIMIT 1
(18, '0011633666', 'IN', '0000-00-00', '0000-00-00')
Query Executing: INSERT INTO access_logs(rf_id, current_state) VALUES ("0011633666", "OUT")
INSERT INTO access_logs(rf_id, current_state) VALUES ("0011633666", "OUT") failed because of: This result object does not return rows. It has been closed automatically.
ALLOW
Verifying state: 0011633666
gate being used: IN
Query Executing: SELECT * FROM users WHERE rf_id="0011633666" 
Query Executing: SELECT * FROM access_logs WHERE rf_id="0011633666" ORDER BY id  DESC LIMIT 1
(19, '0011633666', 'OUT', '0000-00-00', '0000-00-00')
Query Executing: INSERT INTO access_logs(rf_id, current_state) VALUES ("0011633666", "IN")
INSERT INTO access_logs(rf_id, current_state) VALUES ("0011633666", "IN") failed because of: This result object does not return rows. It has been closed automatically.
ALLOW
Verifying state: 
gate being used: IN
Query Executing: SELECT * FROM users WHERE rf_id="" 
user with card  does not exist
